export const colors = {
    white: '#FFFFFF',
    page: '#FFFFFF',
    surface: '#FFFFFF',
    ink: '#222222',
    black: '#000000',
    secondary: '#6C6C6C',
    tertiary: '#717171',
    hairline: '#DDDDDD',
    hairlineSoft: '#EBEBEB',
    brand: '#FF385C',
    reserve: '#D70466',
    continuePink: '#F22A54',
    searchPink: '#E51D56',
    chipBg: '#F7F7F7',
    chipSelected: '#E3E2E0',
    chipBorder: '#DDDDDD',
    counterCircle: '#F2F2F2',
    guestFavBg: 'rgba(255,255,255,0.95)',
    guestFavInk: '#222222',
    star: '#222222',
    navInactive: '#6C6C6C',
    navActive: '#DA1249',
    pillBorder: '#DDDDDD',
    scrim: 'rgba(0,0,0,0.35)',
    iconGray: '#222222',
    ratingPillBg: '#F7F7F7',
    mapBg: '#E8ECEF',
    mapWater: '#AADCE8',
    mapRoad: '#FFFFFF',
    mapBlock: '#DFE5E8',
    pinBg: '#222222',
    pinText: '#FFFFFF',
    selectedTab: '#222222',
} as const;
export const fontFiles = {
    'Roboto-400': require('../assets/fonts/Roboto_400Regular.ttf'),
    'Roboto-500': require('../assets/fonts/Roboto_500Medium.ttf'),
    'Roboto-700': require('../assets/fonts/Roboto_700Bold.ttf'),
    PJS: require('../assets/fonts/PlusJakartaSans-VF.ttf'),
};
export const fonts = {
    sans: 'PJS',
    num: 'Roboto-500',
    roboto400: 'Roboto-400',
    roboto700: 'Roboto-700',
} as const;
export const type = {
    searchPill: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 20, fontWeight: '500' as const, letterSpacing: -0.68, color: colors.ink },
    tab: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 20, fontWeight: '400' as const, letterSpacing: -0.875, color: colors.ink },
    tabSelected: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 20, fontWeight: '400' as const, letterSpacing: -0.875, color: colors.ink },
    sectionTitle: { fontFamily: fonts.sans, fontSize: 18.5, lineHeight: 23.7, fontWeight: '700' as const, letterSpacing: -0.61, color: colors.ink },
    subtitle: { fontFamily: fonts.sans, fontSize: 12.1, lineHeight: 15.85, fontWeight: '400' as const, letterSpacing: 0.15, color: colors.secondary },
    cardTitle: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '600' as const, letterSpacing: -0.35, color: colors.ink },
    cardSub: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '400' as const, color: colors.secondary },
    cardPrice: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 18, fontWeight: '400' as const, letterSpacing: -0.2, color: colors.ink, flexShrink: 0 },
    cardRatingNum: { fontFamily: fonts.num, fontSize: 13, lineHeight: 18, fontWeight: '500' as const, color: colors.ink, flexShrink: 0 },
    rating: { fontFamily: fonts.num, fontSize: 14, lineHeight: 18, fontWeight: '500' as const, color: colors.ink },
    navLabel: { fontFamily: fonts.sans, fontSize: 10, lineHeight: 12, fontWeight: '500' as const, color: colors.navInactive },
    navLabelActive: { fontFamily: fonts.sans, fontSize: 10, lineHeight: 12, fontWeight: '700' as const, color: colors.navActive },
    sheetTitle: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 20, fontWeight: '700' as const, color: colors.ink },
    sheetSectionTitle: { fontFamily: fonts.sans, fontSize: 22, lineHeight: 27, fontWeight: '700' as const, color: colors.ink },
    inputPlaceholder: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 22, fontWeight: '400' as const, color: colors.secondary },
    inputValue: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 22, fontWeight: '600' as const, color: colors.ink },
    destName: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '600' as const, color: colors.ink },
    destSub: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '400' as const, color: colors.secondary },
    counterLabel: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '400' as const, color: colors.ink },
    counterCaption: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '400' as const, color: colors.secondary },
    counterValue: { fontFamily: fonts.roboto400, fontSize: 16, lineHeight: 20, fontWeight: '500' as const, color: colors.ink },
    detailTitle: { fontFamily: fonts.sans, fontSize: 20, lineHeight: 25, fontWeight: '700' as const, color: colors.ink },
    detailSub: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 19, fontWeight: '400' as const, color: colors.secondary },
    detailMeta: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 19, fontWeight: '400' as const, color: colors.ink },
    detailRating: { fontFamily: fonts.num, fontSize: 18, lineHeight: 22, fontWeight: '500' as const, color: colors.ink },
    guestFav: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '600' as const, color: colors.ink },
    hostName: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 19, fontWeight: '600' as const, color: colors.ink },
    hostSub: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '400' as const, color: colors.secondary },
    superhost: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '600' as const, color: colors.ink },
    badgePill: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 16, fontWeight: '600' as const, color: colors.ink },
    priceNow: { fontFamily: fonts.num, fontSize: 20, lineHeight: 24, fontWeight: '500' as const, color: colors.ink },
    priceWas: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '400' as const, color: colors.secondary },
    priceNote: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '400' as const, color: colors.secondary },
    reserveBtn: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '700' as const, color: colors.white },
    photoCatTitle: { fontFamily: fonts.sans, fontSize: 22, lineHeight: 27, fontWeight: '700' as const, color: colors.ink },
    photoCaption: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 19, fontWeight: '400' as const, color: colors.white },
    loginTitle: { fontFamily: fonts.sans, fontSize: 26, lineHeight: 32, fontWeight: '700' as const, color: colors.ink },
    loginInput: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 22, fontWeight: '500' as const, letterSpacing: -0.13, color: colors.secondary },
    loginContinue: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '700' as const, letterSpacing: -0.21, color: colors.white },
    loginOr: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '400' as const, letterSpacing: -1.2, color: colors.ink },
    footerNote: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 17, fontWeight: '600' as const, color: colors.ink },
    resultTitle: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 19, fontWeight: '600' as const, color: colors.ink },
    resultSub: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '400' as const, color: colors.secondary },
    filterChip: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 16, fontWeight: '600' as const, color: colors.ink },
    overHomes: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18, fontWeight: '700' as const, color: colors.ink },
    mapPin: { fontFamily: fonts.num, fontSize: 15, lineHeight: 18, fontWeight: '500' as const, color: colors.ink },
    resultsChip: { fontFamily: fonts.sans, fontSize: 12.6, lineHeight: 16, fontWeight: '400' as const, letterSpacing: -0.72, color: colors.ink },
    resultsTitle: { fontFamily: fonts.sans, fontSize: 14.9, lineHeight: 18.2, fontWeight: '600' as const, letterSpacing: -0.81, color: colors.ink },
    resultsSub: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 15.6, fontWeight: '400' as const, letterSpacing: -0.97, color: colors.secondary },
    resultsCount: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '700' as const, letterSpacing: -0.61, color: colors.ink },
    pdpTitle: { fontFamily: fonts.sans, fontSize: 26, lineHeight: 32, fontWeight: '700' as const, letterSpacing: -1.15, color: colors.ink, textAlign: 'center' as const },
    pdpSub: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '400' as const, letterSpacing: -0.966, color: colors.secondary, textAlign: 'center' as const },
    pdpMeta: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '400' as const, letterSpacing: -0.4, color: colors.secondary, textAlign: 'center' as const },
    pdpRating: { fontFamily: fonts.roboto700, fontSize: 18.2, lineHeight: 23.7, fontWeight: '500' as const, letterSpacing: -0.65, color: colors.ink },
    pdpGuestFav: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 18.4, fontWeight: '700' as const, letterSpacing: -0.62, color: colors.ink },
    pdpChip: { fontFamily: fonts.sans, fontSize: 11.7, lineHeight: 14.2, fontWeight: '500' as const, letterSpacing: -0.5625, color: colors.tertiary },
    pdpHostName: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20.7, fontWeight: '600' as const, letterSpacing: -0.56, color: colors.ink },
    pdpHostSub: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '400' as const, letterSpacing: -0.44, color: colors.secondary },
    pdpBlockTitle: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '600' as const, letterSpacing: -0.6, color: colors.ink },
    pdpBlockDesc: { fontFamily: fonts.sans, fontSize: 14, lineHeight: 18.2, fontWeight: '400' as const, letterSpacing: -0.44, color: colors.secondary },
    pdpBody: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 21.1, fontWeight: '400' as const, letterSpacing: -0.38, color: colors.ink },
    pdpCounter: { fontFamily: fonts.sans, fontSize: 12, lineHeight: 15.6, fontWeight: '600' as const, letterSpacing: -0.2, color: colors.white },
    pdpPriceNow: { fontFamily: fonts.num, fontSize: 21, lineHeight: 25.8, fontWeight: '500' as const, color: colors.ink },
    pdpPriceNote: { fontFamily: fonts.sans, fontSize: 12.5, lineHeight: 15.6, fontWeight: '400' as const, letterSpacing: -0.36, color: colors.secondary },
    pdpReserve: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 20, fontWeight: '700' as const, color: colors.white },
    tourTitle: { fontFamily: fonts.sans, fontSize: 16.5, lineHeight: 20.7, fontWeight: '600' as const, letterSpacing: -0.62, color: colors.ink },
    tourTab: { fontFamily: fonts.sans, fontSize: 13, lineHeight: 15.6, fontWeight: '400' as const, letterSpacing: -0.44, color: colors.secondary },
    tourRoomTitle: { fontFamily: fonts.sans, fontSize: 22, lineHeight: 28.7, fontWeight: '700' as const, letterSpacing: -1.1, color: colors.ink },
    tourRoomCaption: { fontFamily: fonts.sans, fontSize: 15, lineHeight: 18.2, fontWeight: '400' as const, letterSpacing: -0.36, color: colors.secondary },
} as const;
export const space = {
    frameWidth: 393,
    frameHeight: 777,
    contentPad: 24,
    searchPillTop: 12,
    searchPillLeft: 24,
    searchPillWidth: 345,
    searchPillHeight: 56,
    searchPillRadius: 28,
    searchIconBox: 12,
    searchIconGap: 8,
    tabGap: 16,
    tabsTop: 84,
    tabsHeight: 40.4,
    tabPadLeft: 16,
    tabPadRight: 14.2,
    tabIconBox: 16,
    tabIconGap: 6.2,
    tabChipGap: 8,
    headerHeight: 124.5,
    cardWidth: 166.7,
    cardGap: 12,
    cardHeightRow1: 201.2,
    cardHeightRow2: 217.2,
    cardHeightRow2Mid: 201.2,
    cardImageHeight: 158,
    cardRadius: 12,
    cardImageRadius: 12,
    row1HeadingTop: 26.25,
    row1RailGap: 16.3,
    row2HeadingTop: 24,
    row2RailGap: 14.1,
    footerNoteTop: 651.7,
    footerNoteLeft: 100.1,
    footerNoteWidth: 181.2,
    footerNoteHeight: 40,
    sheetPad: 16,
    segTop: 30.9,
    stepRowHeight: 60,
    counterRowHeight: 56,
    navTop: 721,
    navHeight: 55,
    navItemWidth: 75,
    navItemHeight: 56,
    navPadX: 4,
} as const;
export const nav = {
    top: 722,
    height: 55,
    itemWidth: 75,
    itemHeight: 56,
    iconSize: 24,
    labelTop: 30,
    labelSize: 10,
} as const;
export const radii = {
    pill: 24,
    card: 12,
    cardImage: 12,
    sheet: 16,
    sheetTop: 16,
    chip: 20,
    circle: 999,
    counterBtn: 28,
    stepRadius: 14,
} as const;
export const shadow = {
    card: { shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
    pill: { shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 4 },
    nav: { shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: -2 }, elevation: 3 },
    sheet: { shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 12, shadowOffset: { width: 0, height: -4 }, elevation: 5 },
} as const;
export const themes = {
    light: colors,
    dark: {
        ...colors,
        white: '#1A1A1A',
        page: '#121212',
        surface: '#1A1A1A',
        ink: '#EDEDED',
        black: '#000000',
        secondary: '#A0A0A0',
        tertiary: '#8A8A8A',
        hairline: '#2C2C2C',
        hairlineSoft: '#242424',
    },
} as const;
export const frame = { width: 393, height: 777 } as const;
